name: Windows CRD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chrome Remote Desktop
        run: |
          # Paste the PowerShell commands directly from Google here
          # For example:
          # $env:CHROME_REMOTE_DESKTOP_DEFAULT_DESKTOP_SIZES = "1366x768"
          # $env:DISPLAY= ":99"
          # echo "Your PowerShell commands here"

      # Additional steps can be added if needed

