name: Windows CRD

on:
  workflow_dispatch:
    inputs:
      powershell-commands:
        description: 'PowerShell commands for CRD setup'
        required: true
      pin-code:
        description: 'Six-digit PIN code for CRD login'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chrome Remote Desktop
        run: |
          $crdCommands = ${{ github.event.inputs.powershell-commands }}
          $pinCode = ${{ github.event.inputs.pin-code }}

          # Use $crdCommands and $pinCode in your PowerShell commands
